spring.application.name=planting
spring.datasource.url=jdbc:mysql://localhost:3306/nurserydb
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#$env:DATASOURCE_URL="jdbc:mysql://localhost:3306/nurserydb?useSSL=false&serverTimezone=UTC"
#$env:DATASOURCE_USER="root"
#$env:DATASOURCE_PASSWORD="1234"
spring.thymeleaf.cache=false
server.port=5000